[package]
name = "aloroid/cheapnet"
description = "A cheap networking library designed for safety."
license = "MIT"
version = "0.2.0-rc2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "LICENSE", "src"]
exclude = ["test", ".gitattributes", ".gitignore", "CHANGELOG.md", "export.project.json", "README.md", "sourcemap.json", "wally.lock", ".vscode"]

[dependencies]
t = "aloroid/t@3.1.1"
Signal = "sleitnick/signal@1.3.0"