[package]
name = "aloroid/cheapnet"
description = "A cheap networking library designed for safety."
license = "MIT"
version = "0.5.0-rc4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "LICENSE", "src"]
exclude = [
	"test",
	".gitattributes",
	".gitignore",
	"CHANGELOG.md",
	"export.project.json",
	"README.md",
	"sourcemap.json",
	"docs",
	".github"
]