[package]
name = "aloroid/cheapnet"
description = "A cheap networking library designed for safety."
license = "MIT"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "LICENSE", "src"]

[dependencies]
t = "aloroid/t@3.1.1"
Signal = "sleitnick/signal@1.3.0"